services:
  BWCMS.Site:
    class: Bellwether\BWCMSBundle\Classes\SiteManager
    arguments: [@service_container,@request_stack]
  BWCMS.Preference:
    class: Bellwether\BWCMSBundle\Classes\PreferenceManager
    arguments: [@service_container,@request_stack]
  BWCMS.Content:
    class: Bellwether\BWCMSBundle\Classes\ContentManager
    arguments: [@service_container,@request_stack]
  BWCMS.Media:
    class: Bellwether\BWCMSBundle\Classes\MediaManager
    arguments: [@service_container,@request_stack]
  BWCMS.Form.Type.Content:
    class: Bellwether\BWCMSBundle\Form\Type\ContentType
    arguments: [@service_container]
    tags:
      - { name: form.type , alias: bwcms_content }
  BWCMS.Form.Type.Collection:
    class: Bellwether\BWCMSBundle\Form\Type\CollectionType
    tags:
      - { name: form.type , alias: bwcms_collection }
  BWCMS.AdminMenu:
      class: Bellwether\BWCMSBundle\Classes\AdminMenuManager
      arguments: ["@knp_menu.factory",@service_container,@request_stack]
  BWCMS.AdminMenu.Left:
      class: Knp\Menu\MenuItem
      factory_service: BWCMS.AdminMenu
      factory_method: buildLeftMainMenu
      arguments: ["@request"]
      scope: request
      tags:
          - { name: knp_menu.menu, alias: AdminMenu.Left }
  BWCMS.AdminMenu.Right:
      class: Knp\Menu\MenuItem
      factory_service: BWCMS.AdminMenu
      factory_method: buildRightMainMenu
      arguments: ["@request"]
      scope: request
      tags:
          - { name: knp_menu.menu, alias: AdminMenu.Right }
  BWCMS.KernelEventListener:
        class: Bellwether\BWCMSBundle\EventListener\KernelEventListener
        arguments: [@kernel,@service_container,@request_stack]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishRequest }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }