services:
  BWCMS.Site:
    class: Bellwether\BWCMSBundle\Classes\SiteManager
    arguments: [@service_container,@request_stack]
  BWCMS.Content:
    class: Bellwether\BWCMSBundle\Classes\ContentManager
    arguments: [@service_container,@request_stack]
  BWCMS.Media:
    class: Bellwether\BWCMSBundle\Classes\MediaManager
    arguments: [@service_container,@request_stack]
  BWCMS.AdminMenu:
      class: Bellwether\BWCMSBundle\Classes\AdminMenuManager
      arguments: [@service_container,@request_stack]
  BWCMS.KernelEventListener:
        class: Bellwether\BWCMSBundle\EventListener\KernelEventListener
        arguments: [@service_container,@request_stack]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishRequest }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }